#!/bin/zsh

cd /Users/eccentricayman/.zprezto/runcoms

#light terminal theme
theme=$(awk 'NR==19 {$0="source /Users/eccentricayman/.config/base16-shell/scripts/base16-brewer.sh"} { print }' zshrc)
rm -rf zshrc
echo $theme > zshrc

#dark mode off
osascript -e 'tell application "System Events"' -e 'tell appearance preferences' -e 'set dark mode to true' -e 'end tell' -e 'end tell'

#get rid of neofetch printing
neofetch=$(awk 'NR==22 {$0="#neofetch --image ~/Pictures/boo2.png"} { print }' zshrc)
rm -rf zshrc
echo $neofetch > zshrc

source zshrc

neofetch=$(awk 'NR==22 {$0="neofetch --image ~/Pictures/boo2.png"} { print }' zshrc)
rm -rf zshrc
echo $neofetch > zshrc

#night.png in pictures background
osascript -e 'tell application "System Events" to set picture of every desktop to ("/Users/eccentricayman/Pictures/night.jpg" as POSIX file as alias)'
